spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/moviedb}
spring.datasource.username=${DB_USERNAME:movieuser}
spring.datasource.password=${DB_PASSWORD:moviepass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

omdb.api.url=https://www.omdbapi.com/
omdb.api.key=${OMDB_API_KEY}

server.port=${PORT:8080}