spring.application.name=backend

# DATABASE
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/moviedb}
spring.datasource.username=${DB_USERNAME:movieuser}
spring.datasource.password=${DB_PASSWORD:moviepass}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# OMDB
omdb.api.url=https://www.omdbapi.com/
omdb.api.key=${OMDB_API_KEY}

# SERVER
server.port=${PORT:8080}

# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}